name: Manual and Weekly Data Pump

on:
  schedule:
    - cron: '0 13 * * 1' # Runs every Monday at 8 AM EST
  workflow_dispatch: # THIS adds the manual "Run" button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas gspread google-auth requests

      - name: Run the script
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
          CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
        run: python main.py
